version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
    - ./sql-data/db:var/lib/mysql
    ports: 
    - 3336:3306
    environment:
      MYSQL_ROOT_PASSWORD: "JXr-t/hx84"
      MYSQL_DATABASE: "db_test"
