version: "3"

services:
  mysql:
    build: .
    container_name: mysql
    restart: always
    ports: 
    - 3336:3306
    environment:
      MYSQL_ROOT_PASSWORD: "JXr-t/hx84"
      MYSQL_DATABASE: "db_test"
    volumes:
    - ./schemas:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge




